# Data Manipulation Studio

For this studio, we will revisit the data set from our last studio. If you recall, California farmers were looking for advice on growing pumpkins. We will use the same [pumpkins dataset](https://www.kaggle.com/usda/a-year-of-pumpkin-prices) as provided by the U.S. Department of Agriculture. You may have to clean data in the process of data manipulation, so feel free to pull up your notebook from the last class's studio.

We will now be focusing our attention on a different region in the United States, the Northeast. When you open up the `dataset` folder, you will have 13 CSVs, including the San Francisco and Los Angeles data from the last lesson. The 13 CSVs are each a different terminal market in the United States.

A **terminal market** is a central site, often in a metropolitan area, that serves as an assembly and trading place for commodities. Terminal markets for agricultural commodities are usually at or near major transportation hubs. [Definition Source](https://en.wikipedia.org/wiki/Terminal_market#:~:text=A%20terminal%20market%20is%20a,or%20near%20major%20transportation%20hubs)

## Getting Started

Import the CSVs for each of the following cities: Baltimore, Boston, New York, and Philadelphia. Set up a dataframe for each city.

In [49]:
# Import the necessary libraries and CSVs. Make some dataframes!
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df1 = pd.read_csv("dataset/baltimore_9-24-2016_9-30-2017.csv")
df2 = pd.read_csv("dataset/boston_9-24-2016_9-30-2017.csv")
df3 = pd.read_csv("dataset/new-york_9-24-2016_9-30-2017.csv")
df4 = pd.read_csv("dataset/philadelphia_9-24-2016_9-30-2017.csv")

print(df_baltimore)

    Commodity Name  City Name             Package      Variety Sub Variety  \
0         PUMPKINS  BALTIMORE        24 inch bins          NaN         NaN
1         PUMPKINS  BALTIMORE        24 inch bins          NaN         NaN
2         PUMPKINS  BALTIMORE        24 inch bins  HOWDEN TYPE         NaN
3         PUMPKINS  BALTIMORE        24 inch bins  HOWDEN TYPE         NaN
4         PUMPKINS  BALTIMORE        24 inch bins  HOWDEN TYPE         NaN
..             ...        ...                 ...          ...         ...
148       PUMPKINS  BALTIMORE  1/2 bushel cartons    MINIATURE         NaN
149       PUMPKINS  BALTIMORE  1/2 bushel cartons    MINIATURE         NaN
150       PUMPKINS  BALTIMORE  1/2 bushel cartons    MINIATURE  ROUND TYPE
151       PUMPKINS  BALTIMORE  1/2 bushel cartons    MINIATURE  ROUND TYPE
152       PUMPKINS  BALTIMORE  1/2 bushel cartons    MINIATURE  ROUND TYPE

           Date  Low Price  High Price  Mostly Low  Mostly High        Origin  \
0    04/29/2017        270       280.0         270        280.0           NaN
1    05/06/2017        270       280.0         270        280.0           NaN
2    09/24/2016        160       160.0         160        160.0      DELAWARE
3    09/24/2016        160       160.0         160        160.0      VIRGINIA
4    11/05/2016         90       100.0          90        100.0      MARYLAND
..          ...        ...         ...         ...          ...           ...
148  09/30/2017         18        18.0          18         18.0      MARYLAND
149  09/30/2017         18        18.0          18         18.0  PENNSYLVANIA
150  09/24/2016         15        15.0          15         15.0      MARYLAND
151  10/01/2016         15        15.0          15         15.0      MARYLAND
152  10/08/2016         15        15.0          15         15.0      MARYLAND

    Item Size   Color Unit of Sale Repack
0         lge     NaN          NaN      E
1         lge     NaN          NaN      E
2         med     NaN          NaN      N
3         med     NaN          NaN      N
4         lge     NaN          NaN      N
..        ...     ...          ...    ...
148       NaN  ORANGE          NaN      N
149       NaN  ORANGE          NaN      N
150       sml     NaN          NaN      N
151       sml     NaN          NaN      N
152       sml     NaN          NaN      N

[153 rows x 15 columns]

## Clean Your Data

In the last lesson, we cleaned the data related to San Francisco. Pull up your notebook from the last lesson and use it as a reference to clean up these new dataframes.

In [50]:
# Clean your data here!
for df in [df1, df2, df3, df4]:
    for col in df.columns:
        pct_missing = np.mean(df[col].isnull())
        print('{} - {}%'.format(col, round(pct_missing * 100)))

df1_clean = df1.drop(['Type','Grade','Origin District','Environment','Quality','Condition','Appearance','Storage','Crop','Trans Mode'], axis=1)
df2_clean = df2.drop(['Type','Grade','Origin District','Environment','Quality','Condition','Appearance','Storage','Crop','Trans Mode'], axis=1)
df3_clean = df3.drop(['Type','Grade','Origin District','Environment','Quality','Condition','Appearance','Storage','Crop','Trans Mode'], axis=1)
df4_clean = df4.drop(['Type','Grade','Origin District','Environment','Quality','Condition','Appearance','Storage','Crop','Trans Mode'], axis=1)

print(df1_clean)

Commodity Name - 0%
City Name - 0%
Type - 100%
Package - 0%
Variety - 1%
Sub Variety - 84%
Grade - 100%
Date - 0%
Low Price - 0%
High Price - 0%
Mostly Low - 0%
Mostly High - 0%
Origin - 3%
Origin District - 100%
Item Size - 16%
Color - 80%
Environment - 100%
Unit of Sale - 84%
Quality - 100%
Condition - 100%
Appearance - 100%
Storage - 100%
Crop - 100%
Repack - 0%
Trans Mode - 100%
Commodity Name - 0%
City Name - 0%
Type - 100%
Package - 0%
Variety - 0%
Sub Variety - 92%
Grade - 100%
Date - 0%
Low Price - 0%
High Price - 0%
Mostly Low - 0%
Mostly High - 0%
Origin - 0%
Origin District - 81%
Item Size - 1%
Color - 14%
Environment - 100%
Unit of Sale - 87%
Quality - 100%
Condition - 100%
Appearance - 100%
Storage - 100%
Crop - 100%
Repack - 0%
Trans Mode - 100%
Commodity Name - 0%
City Name - 0%
Type - 100%
Package - 0%
Variety - 0%
Sub Variety - 84%
Grade - 100%
Date - 0%
Low Price - 0%
High Price - 0%
Mostly Low - 0%
Mostly High - 0%
Origin - 0%
Origin District - 87%
Item Size - 7%
Color - 81%
Environment - 100%
Unit of Sale - 78%
Quality - 100%
Condition - 100%
Appearance - 100%
Storage - 100%
Crop - 100%
Repack - 0%
Trans Mode - 100%
Commodity Name - 0%
City Name - 0%
Type - 100%
Package - 0%
Variety - 0%
Sub Variety - 79%
Grade - 100%
Date - 0%
Low Price - 0%
High Price - 0%
Mostly Low - 0%
Mostly High - 0%
Origin - 0%
Origin District - 100%
Item Size - 21%
Color - 100%
Environment - 100%
Unit of Sale - 81%
Quality - 100%
Condition - 100%
Appearance - 100%
Storage - 100%
Crop - 100%
Repack - 0%
Trans Mode - 100%
    Commodity Name  City Name             Package      Variety Sub Variety  \
0         PUMPKINS  BALTIMORE        24 inch bins          NaN         NaN
1         PUMPKINS  BALTIMORE        24 inch bins          NaN         NaN
2         PUMPKINS  BALTIMORE        24 inch bins  HOWDEN TYPE         NaN
3         PUMPKINS  BALTIMORE        24 inch bins  HOWDEN TYPE         NaN
4         PUMPKINS  BALTIMORE        24 inch bins  HOWDEN TYPE         NaN
..             ...        ...                 ...          ...         ...
148       PUMPKINS  BALTIMORE  1/2 bushel cartons    MINIATURE         NaN
149       PUMPKINS  BALTIMORE  1/2 bushel cartons    MINIATURE         NaN
150       PUMPKINS  BALTIMORE  1/2 bushel cartons    MINIATURE  ROUND TYPE
151       PUMPKINS  BALTIMORE  1/2 bushel cartons    MINIATURE  ROUND TYPE
152       PUMPKINS  BALTIMORE  1/2 bushel cartons    MINIATURE  ROUND TYPE

           Date  Low Price  High Price  Mostly Low  Mostly High        Origin  \
0    04/29/2017        270       280.0         270        280.0           NaN
1    05/06/2017        270       280.0         270        280.0           NaN
2    09/24/2016        160       160.0         160        160.0      DELAWARE
3    09/24/2016        160       160.0         160        160.0      VIRGINIA
4    11/05/2016         90       100.0          90        100.0      MARYLAND
..          ...        ...         ...         ...          ...           ...
148  09/30/2017         18        18.0          18         18.0      MARYLAND
149  09/30/2017         18        18.0          18         18.0  PENNSYLVANIA
150  09/24/2016         15        15.0          15         15.0      MARYLAND
151  10/01/2016         15        15.0          15         15.0      MARYLAND
152  10/08/2016         15        15.0          15         15.0      MARYLAND

    Item Size   Color Unit of Sale Repack
0         lge     NaN          NaN      E
1         lge     NaN          NaN      E
2         med     NaN          NaN      N
3         med     NaN          NaN      N
4         lge     NaN          NaN      N
..        ...     ...          ...    ...
148       NaN  ORANGE          NaN      N
149       NaN  ORANGE          NaN      N
150       sml     NaN          NaN      N
151       sml     NaN          NaN      N
152       sml     NaN          NaN      N

[153 rows x 15 columns]

## Combine Your Data

Now that you have four clean sets of data, combine all four into one dataframe that represents the entire Northeast region.

In [51]:
# Combine the four dataframes into one!
df_concat = pd.concat([df1_clean, df2_clean, df3_clean, df4_clean], axis=0)
print(df_concat)

   Commodity Name     City Name             Package      Variety Sub Variety  \
0        PUMPKINS     BALTIMORE        24 inch bins          NaN         NaN
1        PUMPKINS     BALTIMORE        24 inch bins          NaN         NaN
2        PUMPKINS     BALTIMORE        24 inch bins  HOWDEN TYPE         NaN
3        PUMPKINS     BALTIMORE        24 inch bins  HOWDEN TYPE         NaN
4        PUMPKINS     BALTIMORE        24 inch bins  HOWDEN TYPE         NaN
..            ...           ...                 ...          ...         ...
52       PUMPKINS  PHILADELPHIA  1/2 bushel cartons    MINIATURE   FLAT TYPE
53       PUMPKINS  PHILADELPHIA  1/2 bushel cartons    MINIATURE   FLAT TYPE
54       PUMPKINS  PHILADELPHIA  1/2 bushel cartons    MINIATURE   FLAT TYPE
55       PUMPKINS  PHILADELPHIA  1/2 bushel cartons    MINIATURE   FLAT TYPE
56       PUMPKINS  PHILADELPHIA  1/2 bushel cartons    MINIATURE   FLAT TYPE

          Date  Low Price  High Price  Mostly Low  Mostly High    Origin  \
0   04/29/2017        270       280.0         270        280.0       NaN
1   05/06/2017        270       280.0         270        280.0       NaN
2   09/24/2016        160       160.0         160        160.0  DELAWARE
3   09/24/2016        160       160.0         160        160.0  VIRGINIA
4   11/05/2016         90       100.0          90        100.0  MARYLAND
..         ...        ...         ...         ...          ...       ...
52  11/05/2016         16        18.0          16         18.0      OHIO
53  08/26/2017         18        20.0          18         20.0  MICHIGAN
54  09/16/2017         16        16.0          16         16.0      OHIO
55  09/23/2017         15        16.0          15         16.0      OHIO
56  09/30/2017         15        18.0          15         18.0      OHIO

   Item Size Color Unit of Sale Repack
0        lge   NaN          NaN      E
1        lge   NaN          NaN      E
2        med   NaN          NaN      N
3        med   NaN          NaN      N
4        lge   NaN          NaN      N
..       ...   ...          ...    ...
52       NaN   NaN   SHELLACKED      N
53       NaN   NaN   SHELLACKED      N
54       NaN   NaN   SHELLACKED      N
55       NaN   NaN   SHELLACKED      N
56       NaN   NaN   SHELLACKED      N

[674 rows x 15 columns]

## Answer Some Questions

Use `groupby()` and `agg()` to answer the following two questions:

1. What is the mean low and high prices for each type of **unit of sale** in the Northeast region? 
2. For each region, what is the average number of pumpkins per variety that came into terminal markets for the year?

In [17]:
# Put your code here to find the mean low and high prices in the Northeast region for each type of unit of sale.
import pandas as pd

df1 = pd.read_csv("dataset/baltimore_9-24-2016_9-30-2017.csv")
df2 = pd.read_csv("dataset/boston_9-24-2016_9-30-2017.csv")
df3 = pd.read_csv("dataset/new-york_9-24-2016_9-30-2017.csv")
df4 = pd.read_csv("dataset/philadelphia_9-24-2016_9-30-2017.csv")

df1['region'] = 'Northeast'
df2['region'] = 'Northeast'
df3['region'] = 'Northeast'
df4['region'] = 'Northeast'

df = pd.concat([df1, df2, df3, df4], ignore_index=True)
northeast_units = df[df['region'] == 'Northeast'] 

mean_prices = northeast_units.groupby('Commodity Name').agg({
    'Low Price': 'mean',
    'High Price': 'mean'
}).reset_index()

print("Mean Low and High Prices for Each Type of Unit in the Northeast:")
print(mean_prices)

Mean Low and High Prices for Each Type of Unit in the Northeast:
  Commodity Name   Low Price  High Price
0       PUMPKINS  134.183976  150.671365

In [18]:
# Put your code here to find the average number of pumpkins coming into terminal markets of each variety.
df['Commodity Name'] = pd.to_numeric(df['Commodity Name'], errors='coerce')
average_pumpkins_per_variety = df.groupby('Variety')['Commodity Name'].mean().reset_index()

print("Average Number of Pumpkins per Variety:")
print(average_pumpkins_per_variety)

Average Number of Pumpkins per Variety:
                    Variety  Commodity Name
0             BIG MACK TYPE             NaN
1                 BLUE TYPE             NaN
2                CINDERELLA             NaN
3                 FAIRYTALE             NaN
4               HOWDEN TYPE             NaN
5         HOWDEN WHITE TYPE             NaN
6              KNUCKLE HEAD             NaN
7                 MINIATURE             NaN
8  MIXED HEIRLOOM VARIETIES             NaN
9                  PIE TYPE             NaN

## Bonus Mission

Try answering the same questions for the Midwest (Chicago, Detroit, and St. Louis) or the Southeast (Atlanta, Columbia, and Miami) regions.

In [54]:
# Try the bonus mission if you have time!